simulators/common: remove local provider
ethereum/hive pull request #332
Opened 2020-09-28 15:20 UTC by renaynay

This PR removes the option to add a local provider as this functionality is largely unused and adds complexity to adding new test suites / simulations.

Now, it is possible to get the hive host simply by calling 

```go
host, err := hive.New()
```

2020-09-29 09:14 UTC, fjl requested changes

2020-09-29 09:14 UTC, fjl commented on simulators/common/providers/hive/hive.go
> +	return GetInstance(config)
Please add a check which panics if the HIVE_SIMULATOR environment variable is not set.
You can also simplify this by just constructing the HostConfiguration and host objects directly.

2020-09-30 08:23 UTC, holiman commented on simulators/common/providers/hive/hive.go
> +	"github.com/ethereum/hive/simulators/common"
goimports

2020-09-30 08:25 UTC, holiman approved these changes
`+31, -722` -- gotta love it!

2020-09-30 08:25 UTC, holiman commented on simulators/ethereum/graphql/graphql.go
> +	"github.com/ethereum/hive/simulators/common/providers/hive"
goimports :)

2020-09-30 08:25 UTC, holiman commented on simulators/ethereum/sync/sync_test.go
> +	"github.com/ethereum/hive/simulators/common/providers/hive"
...

2020-09-30 10:06 UTC, merged